
# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Step 3. Running GitHub Actions

Once you've added the code above and committed it, head to your Actions tab. Under "Workflows", you should see the "Generate Snake" Action you created above.

Workflow

Click "Run Workflow" and watch your workflow run. You can even expand your workflow and see what's happening in real time.

Running Actions

Once your workflow has finished running, you should have received a green ✅ "build" checkmark. If so, this means your Action is working nicely. If not, you'll have to go through the code and see where the errors are. The "build" status should give you some indication of where your errors lie. You can also compare it with the yaml file on my GitHub Profile README.

Build green

If you have the green "build" ✅ then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

CodeOutput
Step 4. Adding a contribution-eating snake to your profile

Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

SnakeEating

Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?
Git Good (10 Part Series)
1 Using the GitHub CLI to update your repo
2 How to create and pin a gist on GitHub
... 6 more parts...
9 How to create a Profile README for your Organisation
10 How to automatically close your issues once you merge a PR
Top comments (36)
pic
 
kushaltanna24 profile image
•
Jun 3 '22

Work fine.! Here is mine - KushalTanna24
Reply
 
msoftware profile image
•
Jul 9 '21

Great tutorial! Works for me.
Here's mine - github.com/msoftware
Reply
 
gustavohgmartins profile image
•
Sep 3 '21

Awsome! How did you change the background-color?
Reply
 
mishmanners profile image
•
Sep 3 '21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.
Thread
 
gustavohgmartins profile image
•
Sep 3 '21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voilá
Thread
 
mishmanners profile image
•
Sep 3 '21

Awesome! Glad to be of help 😄
Reply
 
l3on06 profile image
•
Feb 17

Hello everyone, before proceeding, please navigate to 'Settings -> Actions -> General -> Workflow Permissions' in your README.md file and select 'Read and Write' permissions. This is important because if you have other permissions selected, it may result in errors.
Reply
 
jakon62508112 profile image
•
Jan 21 • Edited on Jan 21

Getting this error when I try to run workflow and after it fails:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Reply
 
shuvajitgeek profile image
•
Feb 2

go to setting -> action -> and check the workflow as read and write
(run build again) hopefully you will not get error
Reply
 
bpolaswar profile image
•
Oct 17 '21

Great worked for me. See github.com/bpolaswar
Thanks.
Reply
 
hoangtien_2k3 profile image
•
Jan 29 • Edited on Jan 29

It does not work for me. Can someone help me?
github.com/hoangtien2k3qx1

Error:
actions/checkout@v2, platane/snk@master, ad-m/github-push-action@master, and crazy-max/ghaction-github-pages@v2.1.3 are not allowed to be used in hoangtien2k3qx1/hoangtien2k3qx1. Actions in this workflow must be: within a repository owned by hoangtien2k3qx1.
Reply
 
ariafatah profile image
•
Sep 18

github.com/ariafatah0711/ariafatah...

Check my github and change this file because I tried the file above only as much as it appears if you want to use the full one I use. And don't forget to give stars😁
Reply
 
ariafatah profile image
•
Sep 18

If the action fails, you can go to repo settings, click action, then select general, and look at the bottom where it says read and write.
Reply
 
shasank27 profile image
•
Aug 8 '21 • Edited on Aug 8

Great tutorial!
But can anyone help me, its not showing all my contributions
github.com/shasank27/shasank27
Reply
 
mishmanners profile image
•
Sep 6 '21 • Edited on Sep 6

Hey Shasank. I can't see it on your profile, but to show all contributions, you need to make sure all contributions are turned on your profile. You can do this in your settings:

github.com/YOUR_PROFILE --> Settings --> Profile

Then scroll down to "Contributions" and check the box that says "Include private contributions on my profile".

Hope that helps.
Reply
 
laurasiiia profile image
•
Jan 3 '22 • Edited on Jan 3

Hi, i did everything right and even got the "build" status. But no output branch was created... why is that? Can someone help me? github.com/laurasiiia
Reply
 
mishmanners profile image
•
Jan 4 '22

I assume you're working off this folder: github.com/laurasiiia/laurasiiia/b...

Since you've got a newer repo (mine account was set up a number of years ago), you have the default branch set to "main". You might need to change the code to be "main" instead of "master".

I created a PR for you: github.com/laurasiiia/laurasiiia/p...
(run it and see if that works)... it might not but worth a shot. Feel free to jump in other people 😄
Reply
 
zieldecastro profile image
•
Sep 15 '21 • Edited on Sep 15

It does not work for me. Can someone help me?
github.com/zieldecastro
instagram.com/zieldecastro/
Reply
 
adityamangal1 profile image
•
Jul 22 '21

Awesome Tutorial! 🐍
Reply
 
hudsonpufferfish profile image
•
Jan 8

I got error "The process '/usr/bin/git' failed with exit code 128". Even though I tried to generate a new personal access token, it didn't work. Anybody has any solution for this error?
Reply
 
viveeeeeek profile image
•
Oct 3 '21

Awesome!
Reply
 
phuocantd profile image
•
Jun 1 '22

How to auto build workflow everyday
Reply
 
wkylin profile image
•
May 1 '22

Here's mine:
github.com/wkylin
Reply
View full discussion (36 comments)
Code of Conduct • Report abuse
profile
Pieces.app
Promoted
The Tool-Between-Tools for Developers

Pieces Copilot

Pieces Copilot understands your unique workflow, providing the most contextual AI coding assistance available.

☁️ Choose from cloud or local LLMs for air-gapped security
🔗 Use it within your favorite tools to reduce context switching
💻 Save and auto-enrich materials on-device for fast sharing and reuse

Download Free
Read next
dev_kiran profile image
🔥Awesome Dev Portfolios - Your Portfolio Belongs Here!😍

Kiran Naragund - Dec 18
calvinmclean profile image
Run Go + HTMX in the Cloud with Acorn

Calvin McLean - Dec 18
atsushiambo profile image
Building a To-Do App with AI Assistance

atsushi-ambo - Nov 26
learnwithparam profile image
Practical example of GraphQL schema design

Paramanantham Harrison - Nov 29
Michelle Mannering
Developer Advocate | Hackathon Queen | International Speaker

    Location
    Australia
    Education
    The University of Melbourne
    Work
    Developer Advocate at GitHub
    Joined
    May 29, 2020

More from Michelle Mannering
Take your career to the next level: GitHub Universe create your own agenda
#github #opensource #ai #machinelearning
Hacktoberfest has started! Are you doing these things?
#github #hacktoberfest #hacktoberfest23 #opensource
How to get more suggestions from GitHub Copilot
#ai #tutorial #githubcopilot #github
profile
Pieces.app
Promoted
Revolutionizing the Developer Workflow: Our Journey with Pieces

Pieces.app image

Imagine a tool that integrates seamlessly across your entire development workflow - from browsing solutions online to writing code in your IDE, and even during team collaborations. Pieces is that tool (or tool-between-tools).

Read full post


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: patelkush
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
